#!/usr/bin/env python3

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = ROOT / "docs" / "qa-dashboard"
MANIFEST_PATH = DOCS_ROOT / "product" / "product-manifest.json"
FRONTEND_ROOT = ROOT / "qa_dashboard" / "frontend_v3"
ROUTER_PATH = FRONTEND_ROOT / "src" / "router" / "AppRouter.jsx"
STORE_ROOT = FRONTEND_ROOT / "src" / "stores"
FEATURE_ROOT = FRONTEND_ROOT / "src" / "features"
BACKEND_APP = ROOT / "qa_dashboard" / "backend" / "app.py"
README_PATH = ROOT / "README.md"
PR_TEMPLATE_PATH = ROOT / ".github" / "PULL_REQUEST_TEMPLATE.md"

README_START = "<!-- QA_DASHBOARD_OVERVIEW_START -->"
README_END = "<!-- QA_DASHBOARD_OVERVIEW_END -->"
PR_START = "<!-- QA_DASHBOARD_DOCS_CHECKLIST_START -->"
PR_END = "<!-- QA_DASHBOARD_DOCS_CHECKLIST_END -->"

GENERATED_NOTICE = (
    "<!-- AUTO-GENERATED BY scripts/generate_qa_dashboard_docs.py. "
    "DO NOT EDIT THIS FILE DIRECTLY. -->"
)


def load_manifest():
    return json.loads(
        MANIFEST_PATH.read_text(
            encoding="utf-8",
        )
    )


def normalize_markdown_cell(value):
    normalized = "" if value is None else str(value)

    return (
        normalized
        .replace("|", "\\|")
        .replace("\n", " ")
        .strip()
    )


def markdown_table(headers, rows):
    header_line = (
        "| "
        + " | ".join(headers)
        + " |"
    )

    separator = (
        "| "
        + " | ".join(
            "---"
            for _ in headers
        )
        + " |"
    )

    body = [
        "| "
        + " | ".join(
            normalize_markdown_cell(
                value,
            )
            for value in row
        )
        + " |"
        for row in rows
    ]

    return "\n".join(
        [
            header_line,
            separator,
            *body,
        ]
    )


def replace_managed_block(
    text,
    start_marker,
    end_marker,
    block,
    anchor=None,
):
    managed = (
        f"{start_marker}\n"
        f"{block.strip()}\n"
        f"{end_marker}"
    )

    start_index = text.find(
        start_marker
    )

    if start_index != -1:
        end_index = text.find(
            end_marker,
            start_index,
        )

        if end_index == -1:
            raise RuntimeError(
                f"Missing marker: {end_marker}"
            )

        end_index += len(
            end_marker
        )

        return (
            text[:start_index].rstrip()
            + "\n\n"
            + managed
            + "\n\n"
            + text[end_index:].lstrip()
        )

    if anchor:
        anchor_index = text.find(
            anchor
        )

        if anchor_index != -1:
            line_end = text.find(
                "\n",
                anchor_index,
            )

            if line_end == -1:
                line_end = len(text)

            return (
                text[: line_end + 1]
                + "\n"
                + managed
                + "\n\n"
                + text[line_end + 1 :]
            )

    return (
        text.rstrip()
        + "\n\n"
        + managed
        + "\n"
    )


def collect_routes():
    if not ROUTER_PATH.exists():
        return []

    text = ROUTER_PATH.read_text(
        encoding="utf-8",
    )

    route_pattern = re.compile(
        r"<Route\s+(?P<body>.*?)\s*/>",
        re.DOTALL,
    )

    routes = []

    for match in route_pattern.finditer(
        text
    ):
        body = match.group("body")

        element_match = re.search(
            r"element=\{\s*"
            r"<([A-Za-z0-9_]+)\s*/>"
            r"\s*\}",
            body,
            re.DOTALL,
        )

        if not element_match:
            continue

        page = element_match.group(1)

        if re.search(
            r"\bindex\b",
            body,
        ):
            route = "/"
        else:
            path_match = re.search(
                r'path="([^"]+)"',
                body,
            )

            if not path_match:
                continue

            route = path_match.group(1)

            if route == "*":
                continue

            route = (
                route
                if route.startswith("/")
                else f"/{route}"
            )

        routes.append(
            {
                "route": route,
                "page": page,
            }
        )

    return routes


def collect_stores():
    if not STORE_ROOT.exists():
        return []

    stores = []

    for path in sorted(
        STORE_ROOT.glob("*.js")
    ):
        text = path.read_text(
            encoding="utf-8",
        )

        stores.append(
            {
                "name": path.stem,
                "file": str(
                    path.relative_to(
                        ROOT
                    )
                ),
                "persistent": (
                    "persist(" in text
                ),
                "versioned": (
                    "version:" in text
                ),
            }
        )

    return stores


def collect_feature_domains():
    if not FEATURE_ROOT.exists():
        return []

    domains = []

    for path in sorted(
        candidate
        for candidate
        in FEATURE_ROOT.iterdir()
        if candidate.is_dir()
    ):
        files = list(
            path.glob("*.js")
        ) + list(
            path.glob("*.jsx")
        )

        domains.append(
            {
                "name": path.name,
                "fileCount": len(files),
            }
        )

    return domains


def collect_api_routes():
    if not BACKEND_APP.exists():
        return []

    text = BACKEND_APP.read_text(
        encoding="utf-8",
    )

    pattern = re.compile(
        r"@app\."
        r"(get|post|put|patch|delete)"
        r"\(\s*['\"]([^'\"]+)['\"]",
        re.IGNORECASE,
    )

    return [
        {
            "method":
                match.group(1).upper(),
            "path":
                match.group(2),
        }
        for match in pattern.finditer(
            text
        )
    ]


def status_counts(items):
    counts = {}

    for item in items:
        status = item.get(
            "status",
            "Unknown",
        )

        counts[status] = (
            counts.get(status, 0)
            + 1
        )

    return counts


def bullet_list(items):
    return "\n".join(
        f"- {item}"
        for item in items
    )


def numbered_list(items):
    return "\n".join(
        f"{index}. {item}"
        for index, item in enumerate(
            items,
            start=1,
        )
    )


def generated_document(content):
    return (
        f"{GENERATED_NOTICE}\n\n"
        f"{content.strip()}\n"
    )


def generate_outputs(manifest):
    product = manifest["product"]
    foundation = manifest[
        "foundation"
    ]
    modules = manifest["modules"]
    requirements = manifest[
        "functionalRequirements"
    ]
    non_functional = manifest[
        "nonFunctionalRequirements"
    ]
    roadmap = manifest["roadmap"]
    routes = collect_routes()
    stores = collect_stores()
    domains = collect_feature_domains()
    api_routes = collect_api_routes()

    module_rows = [
        [
            item["name"],
            item["route"],
            item["status"],
            item["description"],
        ]
        for item in modules
    ]

    requirement_rows = [
        [
            item["id"],
            item["name"],
            item["status"],
            item["description"],
        ]
        for item in requirements
    ]

    nfr_rows = [
        [
            item["id"],
            item["name"],
            item["description"],
        ]
        for item in non_functional
    ]

    roadmap_rows = [
        [
            item["phase"],
            item["name"],
            item["status"],
            item["deliverables"],
        ]
        for item in roadmap
    ]

    route_rows = [
        [
            route["route"],
            route["page"],
        ]
        for route in routes
    ]

    store_rows = [
        [
            store["name"],
            store["file"],
            "Yes"
            if store["persistent"]
            else "No",
            "Yes"
            if store["versioned"]
            else "No",
        ]
        for store in stores
    ]

    domain_rows = [
        [
            domain["name"],
            domain["fileCount"],
        ]
        for domain in domains
    ]

    api_rows = [
        [
            route["method"],
            route["path"],
        ]
        for route in api_routes
    ]

    counts = status_counts(
        requirements
    )

    personas = "\n\n".join(
        (
            f"### {persona['name']}\n\n"
            f"{persona['needs']}"
        )
        for persona in manifest[
            "personas"
        ]
    )

    flow_sections = "\n\n".join(
        (
            f"## {flow['name']}\n\n"
            f"{numbered_list(flow['steps'])}"
        )
        for flow in manifest[
            "userFlows"
        ]
    )

    guide_sections = "\n\n".join(
        (
            f"## {module['name']}\n\n"
            f"**Route:** `{module['route']}`  \n"
            f"**Status:** {module['status']}\n\n"
            f"{module['description']}"
        )
        for module in modules
    )

    docs_index = f"""# {product['name']} Documentation

{product['summary']}

**Version:** `{product['version']}`
**Status:** {product['status']}

## Documentation

- [Product Requirements Document](product/PRD.md)
- [Product Roadmap](product/ROADMAP.md)
- [System Architecture](architecture/ARCHITECTURE.md)
- [Data Model](architecture/DATA-MODEL.md)
- [User Flows](user-flows/USER-FLOWS.md)
- [User Guide](user-guide/USER-GUIDE.md)
- [Documentation Workflow](development/DOCUMENTATION-WORKFLOW.md)
- [Quality Gates](development/QUALITY-GATES.md)
- [Feature Matrix](generated/FEATURE-MATRIX.md)
- [Route Inventory](generated/ROUTE-INVENTORY.md)
- [Store Inventory](generated/STORE-INVENTORY.md)
- [Backend API Inventory](generated/API-INVENTORY.md)
- [Release Status](generated/RELEASE-STATUS.md)
- [Attribution](ATTRIBUTION.md)

## Product Flow

```mermaid
flowchart LR
    Project[Project] --> Environment[Environment]
    Environment --> Asset[Test Asset]
    Asset --> Plan[Test Plan]
    Plan --> Cycle[Test Cycle]
    Cycle --> Execution[Execution]
    Execution --> Result[Results]
    Execution --> Artifact[Artifacts and Logs]
    Result --> Report[Reports]
    Report --> Delivery[Telegram Delivery]
```
"""

    prd = f"""# Product Requirements Document

## Product

**Name:** {product['name']}
**Version:** `{product['version']}`
**Status:** {product['status']}

## Overview

{product['summary']}

## Problem Statement

{manifest['problemStatement']}

## Target Users

{personas}

## Goals

{bullet_list(manifest['goals'])}

## Non-Goals

{bullet_list(manifest['nonGoals'])}

## Product Principles

{bullet_list(manifest['principles'])}

## Functional Requirements

{markdown_table(
    ['ID', 'Requirement', 'Status', 'Description'],
    requirement_rows,
)}

## Non-Functional Requirements

{markdown_table(
    ['ID', 'Requirement', 'Description'],
    nfr_rows,
)}

## Product Modules

{markdown_table(
    ['Module', 'Route', 'Status', 'Description'],
    module_rows,
)}
"""

    architecture = f"""# System Architecture

## Context

{product['name']} extends {foundation['upstreamProduct']} with a structured QA management and traceability interface.

## High-Level Architecture

```mermaid
flowchart LR
    User[QA User] --> UI[React and Vite Dashboard]
    UI --> Router[React Router]
    UI --> State[Zustand Stores]
    State --> Local[(Local Storage MVP)]
    UI --> Service[Frontend Services]
    Service --> API[FastAPI QA Backend]
    API --> Hermes[Hermes Agent]
    Hermes --> Runner[QA Runners and Playwright]
    API --> Store[Execution Store]
    API --> Artifact[Artifacts and Reports]
    API --> Telegram[Telegram Delivery]
```

## Frontend Layers

```mermaid
flowchart TD
    Page[Pages and Route Orchestration]
    Feature[Feature Business Rules]
    Component[Presentational Components]
    Store[Zustand State and Persistence]
    Service[Backend Services]

    Page --> Feature
    Page --> Component
    Page --> Store
    Page --> Service
    Feature --> Component
    Store --> Feature
```

## Runtime Components

- **Frontend:** {foundation['dashboardFrontend']}
- **Backend:** {foundation['executionBackend']}
- **State:** Zustand with localStorage persistence and store migrations
- **Execution:** Hermes Agent and supported QA runners
- **Evidence:** Screenshots, logs, network data, console data, and generated reports
- **Delivery:** Telegram testing and documentation topics

## Feature Domains

{markdown_table(
    ['Feature Domain', 'Source Files'],
    domain_rows,
)}

## Architectural Rules

{bullet_list(manifest['principles'])}
"""

    data_model = """# Data Model

```mermaid
classDiagram
    class Project {
      id
      name
      description
    }

    class Environment {
      id
      projectId
      name
      baseUrl
    }

    class TestAsset {
      id
      projectId
      currentVersionId
      currentVersionNumber
      lifecycleStatus
    }

    class TestAssetVersion {
      versionId
      assetId
      versionNumber
      changeSummary
      snapshot
    }

    class TestPlan {
      id
      projectId
      environmentId
      selectedAssetIds
      selectedAssetSnapshots
      executionSettings
      status
    }

    class TestCycle {
      id
      sourcePlanId
      projectId
      environmentId
      selectedAssetIds
      selectedAssetSnapshots
      status
    }

    class Execution {
      runId
      cycleId
      scopeKey
      status
      progress
    }

    class Artifact {
      artifactId
      runId
      type
      path
    }

    Project "1" --> "*" Environment
    Project "1" --> "*" TestAsset
    TestAsset "1" --> "*" TestAssetVersion
    TestPlan "*" --> "*" TestAssetVersion
    TestPlan "1" --> "*" TestCycle
    TestCycle "1" --> "*" Execution
    Execution "1" --> "*" Artifact
```

## Snapshot Rule

Test Plans and Test Cycles store captured Test Asset definitions. A later edit, archive, or deletion of the live Test Asset must not mutate the historical snapshot.
"""

    user_flows = f"""# User Flows

## End-to-End Flow

```mermaid
flowchart TD
    Start[Open QA Dashboard]
    Start --> Configure[Configure Project and Environment]
    Configure --> Asset[Create or Select Versioned Test Assets]
    Asset --> Plan[Create Test Plan]
    Plan --> Compare[Review Captured vs Live Versions]
    Compare --> Cycle[Create Test Cycle]
    Cycle --> Dispatch[Dispatch Scope Executions]
    Dispatch --> Monitor[Monitor Progress and Logs]
    Monitor --> Result[Review Results and Evidence]
    Result --> Report[Generate QA Report]
    Report --> Deliver[Deliver to Telegram]
```

{flow_sections}
"""

    user_guide = f"""# User Guide

## Getting Started

1. Start the FastAPI QA backend.
2. Start the Vite frontend.
3. Open the dashboard in the browser.
4. Configure a Project and Environment before creating testing records.

## Recommended Operational Sequence

```text
Project
→ Environment
→ Test Asset
→ Test Plan
→ Test Cycle
→ Execution
→ Results and Artifacts
→ Report
→ Delivery
```

{guide_sections}

## Version Traceability

- Editing a Test Asset creates a new immutable version.
- Saving a Test Plan captures the selected asset versions.
- Creating a Test Cycle preserves the definitions used by that cycle.
- Historical snapshots remain available even when the live asset changes.

## Data Safety

- Do not clear browser localStorage unless records have been backed up.
- Never commit `.env`, tokens, credentials, or target-system passwords.
- Review store migration results whenever a persisted schema version changes.
"""

    roadmap_doc = f"""# Product Roadmap

{markdown_table(
    ['Phase', 'Name', 'Status', 'Deliverables'],
    roadmap_rows,
)}
"""

    feature_matrix = f"""# Feature Matrix

This file is generated from `product-manifest.json`.

{markdown_table(
    ['Module', 'Route', 'Status', 'Description'],
    module_rows,
)}

## Functional Requirement Status

{markdown_table(
    ['ID', 'Requirement', 'Status', 'Description'],
    requirement_rows,
)}
"""

    route_inventory = f"""# Frontend Route Inventory

This file is generated from `AppRouter.jsx`.

{markdown_table(
    ['Route', 'Page Component'],
    route_rows,
) if route_rows else 'No frontend routes were detected.'}
"""

    store_inventory = f"""# Zustand Store Inventory

This file is generated from `src/stores`.

{markdown_table(
    ['Store', 'File', 'Persistent', 'Schema Version'],
    store_rows,
) if store_rows else 'No Zustand stores were detected.'}
"""

    api_inventory = f"""# Backend API Inventory

This file is generated from `qa_dashboard/backend/app.py`.

{markdown_table(
    ['Method', 'Path'],
    api_rows,
) if api_rows else 'No FastAPI routes were detected.'}
"""

    release_status = f"""# Release Status

**Product Version:** `{product['version']}`
**Product Status:** {product['status']}

## Functional Requirements

- Implemented: {counts.get('Implemented', 0)}
- In Progress: {counts.get('In Progress', 0)}
- Planned: {counts.get('Planned', 0)}
- Future: {counts.get('Future', 0)}

## Current Focus

{next(
    (
        item['name']
        for item in roadmap
        if item['status']
        == 'In Progress'
    ),
    'No active phase defined.',
)}

## Roadmap

{markdown_table(
    ['Phase', 'Name', 'Status', 'Deliverables'],
    roadmap_rows,
)}
"""

    documentation_workflow = """# Documentation Workflow

## Source of Truth

`docs/qa-dashboard/product/product-manifest.json` contains product intent, module status, requirements, roadmap, and repository metadata.

Technical inventories are derived from source code:

- routes from `AppRouter.jsx`;
- stores from `src/stores`;
- feature domains from `src/features`;
- backend routes from `qa_dashboard/backend/app.py`.

## Local Commands

From `qa_dashboard/frontend_v3`:

```bash
npm run docs:generate
npm run docs:check
npm run verify
```

## Development Rule

When a dashboard feature changes:

1. Update implementation code.
2. Update `product-manifest.json` when product behavior or status changes.
3. Run `npm run docs:generate`.
4. Run lint, build, and documentation checks.
5. Commit code and documentation together.

## CI Behavior

- Pull requests fail when generated documentation is stale.
- Pushes to configured branches regenerate and commit documentation.
- Repository description synchronization runs only when `REPO_ADMIN_TOKEN` is configured.
"""

    attribution = f"""# Attribution

## Hermes Agent

This repository is based on **{foundation['upstreamProduct']}**, maintained by **{foundation['upstreamMaintainer']}**.

The upstream software remains subject to the repository's `{foundation['license']}` license and copyright notice.

## Hermes QA Dashboard

The QA Dashboard is an extension in this fork. It adds QA configuration, versioned Test Assets, Test Planning, Test Cycles, execution monitoring, results, artifacts, reports, and delivery integrations.

The upstream README, license, and attribution are intentionally preserved.
"""

    readme_block = f"""## {product['name']}

> {product['tagline']}

This repository combines the upstream **{foundation['upstreamProduct']}** runtime with a QA automation and traceability product for:

- Projects and Environments;
- versioned Test Assets;
- reusable Test Plans;
- traceable Test Cycles;
- execution monitoring;
- results, logs, and artifacts;
- reporting and Telegram delivery.

**Dashboard version:** `{product['version']}`
**Dashboard status:** {product['status']}

📘 [QA Dashboard product documentation](docs/qa-dashboard/README.md)

The original Hermes Agent documentation continues below.
"""

    pr_checklist = """## QA Dashboard Documentation

- [ ] I ran `npm run lint` in `qa_dashboard/frontend_v3`.
- [ ] I ran `npm run build` in `qa_dashboard/frontend_v3`.
- [ ] I ran `npm run docs:generate`.
- [ ] I ran `npm run docs:check`.
- [ ] I updated `product-manifest.json` when product behavior, scope, or roadmap status changed.
- [ ] I did not commit credentials, tokens, `.env`, or private target-system data.
"""

    outputs = {
        DOCS_ROOT / "README.md":
            generated_document(
                docs_index,
            ),
        DOCS_ROOT / "ATTRIBUTION.md":
            generated_document(
                attribution,
            ),
        DOCS_ROOT / "product" / "PRD.md":
            generated_document(
                prd,
            ),
        DOCS_ROOT / "product" / "ROADMAP.md":
            generated_document(
                roadmap_doc,
            ),
        DOCS_ROOT / "architecture" / "ARCHITECTURE.md":
            generated_document(
                architecture,
            ),
        DOCS_ROOT / "architecture" / "DATA-MODEL.md":
            generated_document(
                data_model,
            ),
        DOCS_ROOT / "user-flows" / "USER-FLOWS.md":
            generated_document(
                user_flows,
            ),
        DOCS_ROOT / "user-guide" / "USER-GUIDE.md":
            generated_document(
                user_guide,
            ),
        DOCS_ROOT / "development" / "DOCUMENTATION-WORKFLOW.md":
            generated_document(
                documentation_workflow,
            ),
        DOCS_ROOT / "generated" / "FEATURE-MATRIX.md":
            generated_document(
                feature_matrix,
            ),
        DOCS_ROOT / "generated" / "ROUTE-INVENTORY.md":
            generated_document(
                route_inventory,
            ),
        DOCS_ROOT / "generated" / "STORE-INVENTORY.md":
            generated_document(
                store_inventory,
            ),
        DOCS_ROOT / "generated" / "API-INVENTORY.md":
            generated_document(
                api_inventory,
            ),
        DOCS_ROOT / "generated" / "RELEASE-STATUS.md":
            generated_document(
                release_status,
            ),
    }

    current_readme = README_PATH.read_text(
        encoding="utf-8",
    )

    outputs[README_PATH] = (
        replace_managed_block(
            current_readme,
            README_START,
            README_END,
            readme_block,
            anchor="# Hermes Agent ☤",
        )
    )

    current_pr_template = (
        PR_TEMPLATE_PATH.read_text(
            encoding="utf-8",
        )
        if PR_TEMPLATE_PATH.exists()
        else ""
    )

    outputs[PR_TEMPLATE_PATH] = (
        replace_managed_block(
            current_pr_template,
            PR_START,
            PR_END,
            pr_checklist,
        )
    )

    return outputs


def apply_outputs(
    outputs,
    check_only=False,
):
    stale = []

    for path, content in outputs.items():
        expected = (
            content.rstrip()
            + "\n"
        )

        current = (
            path.read_text(
                encoding="utf-8",
            )
            if path.exists()
            else ""
        )

        if current == expected:
            continue

        stale.append(
            str(
                path.relative_to(
                    ROOT
                )
            )
        )

        if not check_only:
            path.parent.mkdir(
                parents=True,
                exist_ok=True,
            )

            path.write_text(
                expected,
                encoding="utf-8",
            )

    if check_only and stale:
        print(
            "Documentation is stale:",
            file=sys.stderr,
        )

        for path in stale:
            print(
                f"- {path}",
                file=sys.stderr,
            )

        print(
            "\nRun: npm run docs:generate",
            file=sys.stderr,
        )

        return 1

    if stale:
        action = (
            "Would update"
            if check_only
            else "Updated"
        )

        print(
            f"{action} "
            f"{len(stale)} files:"
        )

        for path in stale:
            print(
                f"- {path}"
            )
    else:
        print(
            "Documentation is already synchronized."
        )

    return 0


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate Hermes QA Dashboard "
            "documentation."
        )
    )

    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Validate generated documentation "
            "without writing files."
        ),
    )

    args = parser.parse_args()

    manifest = load_manifest()
    outputs = generate_outputs(
        manifest
    )

    return apply_outputs(
        outputs,
        check_only=args.check,
    )


if __name__ == "__main__":
    raise SystemExit(main())
